### ISSUE TITLE
[Bug Report]: Android 12 bug report

### ISSUE THREAD

**Issue by MohaNoor** [demola234/smart_liveliness_detection#2]
In ios it's working fine but in android app can not recognize the face and the icon in red and hanging on initializing

**Comment by demola234** [comment]
This has been fixed with the latest beta version  `0.0.1-beta.5`

**Comment by MohaNoor** [comment]
Unfortunately the problem still exist after use last version 

My mobile android version is 12

**Comment by demola234** [comment]
Please kindly share the full scope of your error

**Comment by MohaNoor** [comment]
here the error 


I/flutter ( 6577): Error processing image: PlatformException(InputImageConverterError, java.lang.IllegalArgumentException, null, null)
E/ImageError( 6577): Getting Image failed


i tried all option Deafult style,Custom theme,Custom Challenge etc , And still Cannot recognize the face

**Comment by MohaNoor** [comment]
After investigation, I found that the issue happens because CameraController does not set imageFormatGroup: ImageFormatGroup.yuv420,
which causes ML Kit to fail when processing the camera image.

Could you please update the package to initialize CameraController like this?

dart
Copy
Edit
CameraController(
  camera,
  resolutionPreset,
  imageFormatGroup: ImageFormatGroup.yuv420,
);

maybe this can help or you are can fix by your way 

many thanks

**Comment by MohaNoor** [comment]
here the error


I/flutter ( 6577): Error processing image: PlatformException(InputImageConverterError, java.lang.IllegalArgumentException, null, null)
E/ImageError( 6577): Getting Image failed

**Comment by demola234** [comment]
<img width="377" alt="Image" src="https://github.com/user-attachments/assets/8c0bf8cd-266f-4e7d-8bbe-f9ed0f004a3e" /> Hello @MohaNoor turns out the camara controller already works. Could you please try the latest version of that package to confirm it works for you!

**Comment by MohaNoor** [comment]
I already use the last version 


smart_liveliness_detection: ^0.1.3

**Comment by demola234** [comment]
I will look into it

**Comment by sonalnimgade10** [comment]
Any update on this issue?
